-- Ejecutar UNA VEZ en Supabase > SQL Editor.
-- Crea el estudiante de prueba y copia automáticamente cada resultado a "notas".
do $$ begin
if not exists(select 1 from public.estudiantes where regexp_replace(coalesce(cedula,''),'\D','','g')='88888888') then insert into public.estudiantes(nombre,salon,cedula,correo,es_prueba) values('PRUEBA, ESTUDIANTE','8A','8-888-8888',null,true); else update public.estudiantes set nombre='PRUEBA, ESTUDIANTE',salon='8A',cedula='8-888-8888',es_prueba=true where regexp_replace(coalesce(cedula,''),'\D','','g')='88888888'; end if;
end $$;
create or replace function public.sincronizar_nota_ejercicio_8a() returns trigger language plpgsql security definer set search_path=public as $$
declare e public.estudiantes%rowtype; c integer; t integer; n integer; tema text;
begin if new.salon<>'8A' or new.codigo_examen!~'^cn8a-clase[1-4]-2026$' then return new; end if; select * into e from public.estudiantes where regexp_replace(coalesce(cedula,''),'\D','','g')=regexp_replace(coalesce(new.cedula,''),'\D','','g') and salon='8A' limit 1; if e.id is null then return new; end if; c:=substring(new.codigo_examen from 'clase([1-4])')::integer;t:=case new.tipo_ejercicio when 'quiz' then 1 when 'pareo' then 2 when 'fotos' then 3 else null end;if t is null then return new;end if;n:=((c-1)*3)+t;tema:='Clase '||c||' — '||case new.tipo_ejercicio when 'quiz' then 'Respuesta múltiple' when 'pareo' then 'Pareo de términos' else 'Pareo de fotos' end;delete from public.notas where estudiante_id=e.id and materia='Ciencias Naturales' and tipo='ejercicio' and numero=n and trimestre='Trimestre 3' and origen='ejercicio_automatico_8a';insert into public.notas(correo,estudiante_id,materia,tipo,numero,tema,actividad,fecha,nota,observacion,trimestre,estado,origen) values(e.correo,e.id,'Ciencias Naturales','ejercicio',n,tema,tema,current_date,new.nota_meduca,'Guardada automáticamente al finalizar','Trimestre 3','Activa','ejercicio_automatico_8a');return new;end $$;
drop trigger if exists trg_sincronizar_nota_ejercicio_8a on public.prueba_intentos_practica;create trigger trg_sincronizar_nota_ejercicio_8a after insert or update on public.prueba_intentos_practica for each row execute function public.sincronizar_nota_ejercicio_8a();
do $$ declare eid uuid;begin select id into eid from public.estudiantes where regexp_replace(coalesce(cedula,''),'\D','','g')='88888888' and salon='8A' limit 1;delete from public.notas where estudiante_id=eid and materia='Ciencias Naturales' and tipo='ejercicio' and numero between 1 and 3 and trimestre='Trimestre 3' and origen='ejercicio_automatico_8a';insert into public.notas(correo,estudiante_id,materia,tipo,numero,tema,actividad,fecha,nota,observacion,trimestre,estado,origen) values(null,eid,'Ciencias Naturales','ejercicio',1,'Clase 1 — Respuesta múltiple','Clase 1 — Respuesta múltiple',current_date,4.5,'Nota de ejemplo','Trimestre 3','Activa','ejercicio_automatico_8a'),(null,eid,'Ciencias Naturales','ejercicio',2,'Clase 1 — Pareo de términos','Clase 1 — Pareo de términos',current_date,4.0,'Nota de ejemplo','Trimestre 3','Activa','ejercicio_automatico_8a'),(null,eid,'Ciencias Naturales','ejercicio',3,'Clase 1 — Pareo de fotos','Clase 1 — Pareo de fotos',current_date,5.0,'Nota de ejemplo','Trimestre 3','Activa','ejercicio_automatico_8a');end $$;
