import { supabase } from "./supabase.js";
const temas={7:["La célula y la teoría celular","Tejidos animales y vegetales","Funciones vitales de los seres vivos","Ecosistemas y redes tróficas","Materia, energía y sus transformaciones","La Tierra y el universo"],8:["Sistema circulatorio y tejido sanguíneo","Sistema inmunológico","Reproducción de los organismos","Ecosistemas e interdependencia","Ciencias físicas y químicas","La Tierra y el universo"],9:["Divulgación de investigaciones científicas","Material genético: ADN y ARN","Ciclo celular","Reproducción y desarrollo humano","Genética","Enfermedades genéticas y grupos sanguíneos","Sexualidad responsable","Origen de las especies y evolución","Cambio climático","Movimiento ondulatorio","Energía eléctrica","El sistema solar"]};
const defs=[
["area","(7) Área","Se extrae del programa de estudio."],["competencia","(8) Competencia(s) y rasgos","Se extraen del programa según el contenido."],["objetivo","(9) Objetivo(s) de aprendizaje","Incluya acción, objeto, condición y finalidad."],["conceptual","(10) Contenido conceptual","Se extrae del programa oficial."],["procedimental","(10) Contenido procedimental","Acciones y procesos que realizará el estudiante."],["actitudinal","(10) Contenido actitudinal","Valores y disposiciones promovidos."],["indicador","(11) Indicador(es) de logro","Tareas observables que muestran avances."],["inicio","(12) Actividad(es) de inicio","Explore saberes previos."],["desarrollo","(12) Actividad(es) de desarrollo","Fortalezca aprendizajes mediante práctica."],["cierre","(12) Actividad(es) de cierre","Verifique el logro de los objetivos."],["actuaciones","(13.1) Actuaciones directas","Exposiciones, charlas o sustentaciones."],["entregables","(13.1) Entregables","Informes, resúmenes, álbumes u otros productos."],["criterios","(13.2) Criterios","Pautas para valorar las evidencias."],["diagnostica","(13.3) Diagnóstica / instrumento","Conocimientos que posee el estudiante."],["formativa","(13.3) Formativa / instrumento","Permite observar avances y fortalecer debilidades."],["sumativa","(13.3) Sumativa / instrumento","Valora los desempeños demostrados."],["observaciones","(14) Observaciones","Incidencias durante la implementación."]];
const $=s=>document.querySelector(s),form=$("#plan"),grado=$("#grado"),tema=$("#tema"),trimestre=$("#trimestre");
function pintarCampos(){const c=$("#campos");c.innerHTML=defs.map(([n,l,h],i)=>`<label class="campo ${i===0||i===16?'ancho':''}"><b>${l}<button type="button" title="${h}">?</button></b><textarea name="${n}" rows="${i===6?8:3}"></textarea></label>`).join("")}
function pintarTemas(){tema.innerHTML=temas[grado.value].map(t=>`<option>${t}</option>`).join("");$("#gradoVista").value=grado.value+".º";$("#estadoLibro").classList.toggle("apagado",grado.value!=="9")}
function propuesta(){const t=tema.value.toLowerCase(),libro=grado.value==="9"?"del libro del estudiante":"seleccionada por el docente";const p={area:"Ciencias de la vida",competencia:"Pensamiento científico: analiza fenómenos naturales, formula explicaciones basadas en evidencias y comunica conclusiones con responsabilidad.",objetivo:`Analizar ${t}, mediante la observación, el diálogo y actividades prácticas, para explicar su importancia en situaciones de la vida cotidiana.`,conceptual:tema.value,procedimental:`Observación, comparación, análisis de información y elaboración de representaciones sobre ${t}.`,actitudinal:"Curiosidad científica, participación responsable, respeto por las ideas de los demás y cuidado del ambiente.",indicador:`Explica ${t} mediante ejemplos, vocabulario científico y evidencias obtenidas durante las actividades de aula.`,inicio:`Explorar conocimientos previos mediante una pregunta generadora y una lluvia de ideas sobre ${t}.`,desarrollo:`Analizar una lectura ${libro}, construir un organizador gráfico y resolver en equipos una situación relacionada con ${t}.`,cierre:"Socializar conclusiones, corregir ideas iniciales y completar un boleto de salida.",actuaciones:"Participación, explicación oral, trabajo colaborativo y sustentación.",entregables:"Organizador gráfico, respuestas de la actividad y boleto de salida.",criterios:"Comprensión, claridad, vocabulario científico, precisión, creatividad, responsabilidad y trabajo colaborativo.",diagnostica:"Lluvia de ideas - Registro de observación.",formativa:"Organizador gráfico y trabajo colaborativo - Lista de cotejo.",sumativa:"Producto y explicación final - Rúbrica analítica."};Object.entries(p).forEach(([n,v])=>form.elements[n].value=v);form.scrollIntoView({behavior:"smooth"})}
function datos(){return Object.fromEntries(new FormData(form).entries())}function clave(){return`plan-meduca-${grado.value}`}
function guardar(){localStorage.setItem(clave(),JSON.stringify({grado:grado.value,trimestre:trimestre.value,tema:tema.value,plan:datos()}));$("#guardar").textContent="✓ Guardado"}
function cargar(){const raw=localStorage.getItem(clave());if(!raw)return;try{const x=JSON.parse(raw);trimestre.value=x.trimestre||"I";$("#trimestreVista").value=trimestre.value;Object.entries(x.plan||{}).forEach(([n,v])=>{if(form.elements[n])form.elements[n].value=v})}catch{}}
async function sesion(){const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="login.html";return}const{data:p}=await supabase.from("profesores").select("nombre_profesor").eq("correo_profesor",user.email.toLowerCase()).maybeSingle();if(p?.nombre_profesor&&!form.elements.docente.value)form.elements.docente.value=p.nombre_profesor}
pintarCampos();pintarTemas();$("#trimestreVista").value=trimestre.value;cargar();sesion();grado.onchange=()=>{pintarTemas();cargar()};trimestre.onchange=()=>$("#trimestreVista").value=trimestre.value;$("#generar").onclick=propuesta;$("#guardar").onclick=guardar;$("#imprimir").onclick=()=>print();$("#limpiar").onclick=()=>{if(confirm("¿Limpiar la planificación actual?")){form.reset();$("#gradoVista").value=grado.value+".º";$("#trimestreVista").value=trimestre.value}};
