import { supabase } from './supabase.js';
const BUCKET='vida-estudiantil';let todos=[],rechazoId=null;const $=id=>document.getElementById(id);const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function msg(t,k='info'){const e=$('mensajeVida');e.textContent=t;e.className=`ve-alert show ${k}`;setTimeout(()=>e.classList.remove('show'),5000)}
async function signed(p){const {data}=await supabase.storage.from(BUCKET).createSignedUrl(p,3600);return data?.signedUrl||''}
async function iniciar(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.replace('login.html');return}const {data:p}=await supabase.from('usuarios').select('rol').eq('auth_user_id',user.id).maybeSingle();if(p?.rol!=='admin'){alert('Acceso exclusivo para administración.');location.replace('login.html');return}$('btnSalirVida').onclick=async e=>{e.preventDefault();await supabase.auth.signOut();location.replace('login.html')};['filtroEstado','filtroSalon','buscarEstudiante'].forEach(id=>$(id).addEventListener(id==='buscarEstudiante'?'input':'change',pintar));$('cancelarRechazo').onclick=()=>{$('modalRechazo').classList.remove('open')};$('confirmarRechazo').onclick=confirmarRechazo;await cargar()}
async function cargar(){const {data,error}=await supabase.from('vida_estudiantil_recuerdos').select('*').order('creado_en',{ascending:false});if(error){msg('Ejecuta primero la configuración de Supabase.','error');return}todos=data||[];const salones=[...new Set(todos.map(x=>x.salon).filter(Boolean))].sort();$('filtroSalon').innerHTML='<option value="">Todos los salones</option>'+salones.map(s=>`<option>${esc(s)}</option>`).join('');$('resumenAdmin').textContent=`${todos.filter(x=>x.estado==='pendiente').length} pendientes · ${todos.length} archivos`;pintar()}
async function pintar(){const est=$('filtroEstado').value,sal=$('filtroSalon').value,q=$('buscarEstudiante').value.trim().toLowerCase();const lista=todos.filter(x=>(est==='todos'||x.estado===est)&&(!sal||x.salon===sal)&&(!q||x.nombre_estudiante.toLowerCase().includes(q)));const caja=$('listaRevision');if(!lista.length){caja.innerHTML='<div class="ve-empty">No hay archivos con estos filtros.</div>';return}caja.innerHTML='<div class="ve-empty">Cargando recuerdos…</div>';const html=await Promise.all(lista.map(async d=>{const u=await signed(d.ruta_storage),media=d.tipo==='video'?`<video class="ve-admin-media" controls src="${u}"></video>`:`<img class="ve-admin-media" loading="lazy" src="${u}" alt="${esc(d.titulo)}">`;return `<article class="ve-admin-card" data-id="${d.id}">${media}<h3>${esc(d.titulo)}</h3><div class="ve-person">${esc(d.nombre_estudiante)} · ${esc(d.salon)}</div>${d.descripcion?`<p>${esc(d.descripcion)}</p>`:''}${d.profesor?`<p><strong>Profesor(a):</strong> ${esc(d.profesor)}</p>`:''}<p><span class="ve-status ${d.estado}" style="position:static;display:inline-block">${d.estado}</span></p>${d.motivo_rechazo?`<p><strong>Observación:</strong> ${esc(d.motivo_rechazo)}</p>`:''}<div class="ve-actions"><button class="ve-btn success aprobar">Aprobar</button><button class="ve-btn danger rechazar">Rechazar</button><button class="ve-btn light borrar">Eliminar</button></div></article>`}));caja.innerHTML=html.join('');caja.querySelectorAll('.ve-admin-card').forEach(c=>{const id=c.dataset.id;c.querySelector('.aprobar').onclick=()=>estado(id,'aprobado');c.querySelector('.rechazar').onclick=()=>abrirRechazo(id);c.querySelector('.borrar').onclick=()=>borrar(id)})}
async function estado(id,valor,motivo=null){const {error}=await supabase.from('vida_estudiantil_recuerdos').update({estado:valor,motivo_rechazo:motivo,revisado_en:new Date().toISOString()}).eq('id',id);if(error){msg(error.message,'error');return}const d=todos.find(x=>x.id===id);d.estado=valor;d.motivo_rechazo=motivo;msg(valor==='aprobado'?'Recuerdo aprobado.':'Se envió la corrección al estudiante.','ok');pintar()}
function abrirRechazo(id){rechazoId=id;$('motivoRechazo').value='';$('modalRechazo').classList.add('open');$('motivoRechazo').focus()}
async function confirmarRechazo(){const m=$('motivoRechazo').value.trim();if(!m){alert('Escribe el motivo.');return}$('modalRechazo').classList.remove('open');await estado(rechazoId,'rechazado',m)}
async function borrar(id){const d=todos.find(x=>x.id===id);if(!d||!confirm('¿Eliminar definitivamente este archivo?'))return;const {error:a}=await supabase.storage.from(BUCKET).remove([d.ruta_storage]);if(a){msg(a.message,'error');return}const {error:b}=await supabase.from('vida_estudiantil_recuerdos').delete().eq('id',id);if(b){msg(b.message,'error');return}todos=todos.filter(x=>x.id!==id);msg('Archivo eliminado.','ok');pintar()}
iniciar();
